.git-clone: &git-clone
  name: git-clone
  git:
    enable: true
    submodules: true

.build-amd64: &build-amd64
  name: build-amd64
  runner:
    tags: cnb:arch:amd64
  services:
    - docker
  env:
    IMAGE_TAG: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:linux-amd64
  stages:
    - name: docker login
      script: docker login -u ${CNB_TOKEN_USER_NAME} -p "${CNB_TOKEN}" ${CNB_DOCKER_REGISTRY}
    - name: docker build
      script: docker build -t ${IMAGE_TAG} .
    - name: docker push
      script: docker push ${IMAGE_TAG}
    - name: resolve
      type: cnb:resolve
      options:
        key: build-amd64

.build-arm: &build-arm
  name: build-arm
  runner:
    tags: cnb:arch:arm64:v8
  services:
    - docker
  env:
    IMAGE_TAG: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:develop-linux-arm64
  stages:
    - name: docker login
      script: docker login -u ${CNB_TOKEN_USER_NAME} -p "${CNB_TOKEN}" ${CNB_DOCKER_REGISTRY}
    - name: docker build
      script: docker build -t ${IMAGE_TAG} .
    - name: docker push
      script: docker push ${IMAGE_TAG}
    - name: resolve
      type: cnb:resolve
      options:
        key: build-arm64

develop:
  push:
    - *git-clone
    - *build-amd64
    - *build-arm

    - services:
        - docker
      name: "push"
      env:
        IMAGE_TAG: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:develop
      stages:
        - name: await the amd64
          type: cnb:await
          options:
            key: build-amd64
        - name: await the arm64
          type: cnb:await
          options:
            key: build-arm64
        - name: manifest
          image: cnbcool/manifest
          settings:
            target: ${IMAGE_TAG}
            template: ${IMAGE_TAG}-OS-ARCH
            platforms:
              - linux/amd64
              - linux/arm64
        - name: remove tag
          type: artifact:remove-tag
          options:
            name: ${CNB_REPO_NAME}
            tags:
              - linux-amd64
              - linux-arm64
            type: docker
$:
  tag_push:
    - *git-clone
    - *build-arm
    - services:
        - docker
      name: "push"
      stages:
        - name: await the amd64
          type: cnb:await
          options:
            key: build-amd64
        - name: await the arm64
          type: cnb:await
          options:
            key: build-arm64
        - name: manifest latest
          image: cnbcool/manifest
          settings:
            target: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest
            template: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:OS-ARCH
            platforms:
              - linux/amd64
              - linux/arm64
        - name: manifest version
          image: cnbcool/manifest
          settings:
            target: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:${CNB_BRANCH}
            template: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:OS-ARCH
            platforms:
              - linux/amd64
              - linux/arm64
        - name: remove tag
          type: artifact:remove-tag
          options:
            name: ${CNB_REPO_NAME}
            tags:
              - linux-amd64
              - linux-arm64
            type: docker
