version: '3.8'

services:
  dwz-server:
    container_name: dwz-server
    image: docker.cnb.cool/mliev/open/dwz-server:latest
    restart: always
    ports:
      - "8080"  # 仅暴露给容器网络
    volumes:
      - "./config/:/app/config/"
    environment:
      - TZ=Asia/Shanghai
      - DATABASE_DRIVER=mysql
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_DBNAME=dwz
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=dwz123456
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis123456
      - REDIS_DB=0
      - AUTO_INSTALL=install
      - GIN_MODE=release
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

  dwz-admin:
    container_name: dwz-admin
    image: docker.cnb.cool/mliev/open/dwz-admin-webui:latest
    restart: always
    ports:
      - "8081:80"
    depends_on:
      dwz-server:
        condition: service_healthy
    environment:
      - TZ=Asia/Shanghai
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  mysql:
    image: mysql:5.7
    container_name: dwz-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=dwz123456
      - MYSQL_DATABASE=dwz
      - MYSQL_USER=dwz
      - MYSQL_PASSWORD=dwz123456
      - TZ=Asia/Shanghai
    volumes:
      - "./data/mysql_data:/var/lib/mysql"
    ports:
      - "3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "dwz", "-pdwz123456"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7-alpine
    container_name: dwz-redis
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - "./data/redis_data:/data"
    ports:
      - "6379"
    command: redis-server --requirepass redis123456
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s